name: DuelosPrimsZone
version: 1.0.0
main: lat.primszone.duelos.DuelosPlugin
api-version: 1.21
description: Sistema de Duelos 1v1 con ELO para PrimsZone
authors: [PrimsZone]
depend: [Vault]
softdepend: [FastAsyncWorldEdit, PlaceholderAPI]

commands:
  duelos:
    description: Abre el menú de duelos
    aliases: [pvp, 1v1, combate]
    usage: /duelos
  duelo:
    description: Gestión de duelos
    aliases: [duel]
    usage: /duelo <aceptar|rechazar|salir|rendirse>
  pvpadmin:
    description: Comandos de administración PvP
    permission: duelos.admin
    usage: /pvpadmin <reset|setelo|reload> [jugador] [valor]
  arenaduelos:
    description: Gestión de arenas de duelo
    permission: duelos.admin
    usage: /arenaduelos <crear|spawn1|spawn2|listar|borrar> [nombre]

permissions:
  duelos.play:
    description: Puede jugar duelos
    default: true
  duelos.admin:
    description: Admin de duelos
    default: op
